package launcheruniversae;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JPanel;
import utilidades.Utilidades;
import launcheruniversae.PageBotones;

/**
 *
 * @author Víctor Arroyo
 */
public class MainWindow extends javax.swing.JFrame {

    private PageBotones pagina1 = new PageBotones();

    public MainWindow() {
        initComponents();
//        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        content.setLayout(new BorderLayout());
        Utilidades.showPanel(pagina1, content);
        asignarImagenesEstaticas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        topIcons = new javax.swing.JPanel();
        icoTop1 = new javax.swing.JLabel();
        icoTop2 = new javax.swing.JLabel();
        icoTop3 = new javax.swing.JLabel();
        icoTop4 = new javax.swing.JLabel();
        icoTop5 = new javax.swing.JLabel();
        icoTop6 = new javax.swing.JLabel();
        icoTop7 = new javax.swing.JLabel();
        icoTop8 = new javax.swing.JLabel();
        icoTop9 = new javax.swing.JLabel();
        icoTop10 = new javax.swing.JLabel();
        icoTop11 = new javax.swing.JLabel();
        icoTop12 = new javax.swing.JLabel();
        icoTop13 = new javax.swing.JLabel();
        icoTop14 = new javax.swing.JLabel();
        labelBgImage = new javax.swing.JLabel();

        setTitle("Universae");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(10, 38, 72));
        content.setMaximumSize(new java.awt.Dimension(1430, 730));
        content.setMinimumSize(new java.awt.Dimension(1430, 730));
        content.setLayout(new java.awt.BorderLayout());
        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 1430, 730));

        topIcons.setOpaque(false);
        topIcons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        icoTop1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icoTop1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icoTop1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icoTop1.setMaximumSize(new java.awt.Dimension(80, 80));
        icoTop1.setMinimumSize(new java.awt.Dimension(80, 80));
        icoTop1.setName(""); // NOI18N
        icoTop1.setPreferredSize(new java.awt.Dimension(80, 80));
        icoTop1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icoTop1MouseClicked(evt);
            }
        });
        topIcons.add(icoTop1);

        icoTop2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icoTop2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icoTop2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icoTop2.setPreferredSize(new java.awt.Dimension(80, 80));
        topIcons.add(icoTop2);

        icoTop3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icoTop3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icoTop3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icoTop3.setPreferredSize(new java.awt.Dimension(80, 80));
        topIcons.add(icoTop3);

        icoTop4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icoTop4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icoTop4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icoTop4.setPreferredSize(new java.awt.Dimension(80, 80));
        topIcons.add(icoTop4);

        icoTop5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icoTop5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icoTop5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icoTop5.setPreferredSize(new java.awt.Dimension(80, 80));
        topIcons.add(icoTop5);

        icoTop6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icoTop6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icoTop6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icoTop6.setPreferredSize(new java.awt.Dimension(80, 80));
        topIcons.add(icoTop6);

        icoTop7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icoTop7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icoTop7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icoTop7.setPreferredSize(new java.awt.Dimension(80, 80));
        topIcons.add(icoTop7);

        icoTop8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icoTop8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icoTop8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icoTop8.setPreferredSize(new java.awt.Dimension(80, 80));
        topIcons.add(icoTop8);

        icoTop9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icoTop9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icoTop9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icoTop9.setPreferredSize(new java.awt.Dimension(80, 80));
        topIcons.add(icoTop9);

        icoTop10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icoTop10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icoTop10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icoTop10.setPreferredSize(new java.awt.Dimension(80, 80));
        topIcons.add(icoTop10);

        icoTop11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icoTop11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icoTop11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icoTop11.setPreferredSize(new java.awt.Dimension(80, 80));
        topIcons.add(icoTop11);

        icoTop12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icoTop12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icoTop12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icoTop12.setPreferredSize(new java.awt.Dimension(80, 80));
        topIcons.add(icoTop12);

        icoTop13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icoTop13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icoTop13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icoTop13.setPreferredSize(new java.awt.Dimension(80, 80));
        topIcons.add(icoTop13);

        icoTop14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icoTop14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icoTop14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icoTop14.setPreferredSize(new java.awt.Dimension(80, 80));
        topIcons.add(icoTop14);

        getContentPane().add(topIcons, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 93, 1553, -1));

        labelBgImage.setBackground(new java.awt.Color(10, 38, 72));
        labelBgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/Fondo base.png"))); // NOI18N
        labelBgImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelBgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        getAccessibleContext().setAccessibleDescription("Launcher Universae");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void icoTop1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icoTop1MouseClicked
//        Utilidades.volverHome(content);
        PageBotones nuevaPagina = new PageBotones();
        Utilidades.showPanel(nuevaPagina, content);
    }//GEN-LAST:event_icoTop1MouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

//    private void volverHome(JPanel component) {
//        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(component);
//        if (window instanceof MainWindow) {
//            MainWindow launcher = (MainWindow) window;
//            PageBotones panelBotones = new PageBotones();
//            Utilidades.showPanel(panelBotones, launcher.getContentPanel());
//        }
//    }

    public JPanel getContentPanel() {
        return content;
    }

    private void asignarImagenesEstaticas() {
        Utilidades.setLabelImage(labelBgImage, "src/launcheruniversae/img/Fondo base.png", true);
        Utilidades.setLabelImage(icoTop1, "src/launcheruniversae/img/LauncherButton0.png", true);
        Utilidades.setLabelImage(icoTop2, "src/launcheruniversae/img/LauncherButton1.png", true);
        Utilidades.setLabelImage(icoTop3, "src/launcheruniversae/img/LauncherButton2.png", true);
        Utilidades.setLabelImage(icoTop4, "src/launcheruniversae/img/LauncherButton3.png", true);
        Utilidades.setLabelImage(icoTop5, "src/launcheruniversae/img/LauncherButton4.png", true);
        Utilidades.setLabelImage(icoTop6, "src/launcheruniversae/img/LauncherButton5.png", true);
        Utilidades.setLabelImage(icoTop7, "src/launcheruniversae/img/LauncherButton6.png", true);
        Utilidades.setLabelImage(icoTop8, "src/launcheruniversae/img/LauncherButton7.png", true);
        Utilidades.setLabelImage(icoTop9, "src/launcheruniversae/img/LauncherButton8.png", true);
        Utilidades.setLabelImage(icoTop10, "src/launcheruniversae/img/LauncherButton9.png", true);
        Utilidades.setLabelImage(icoTop11, "src/launcheruniversae/img/LauncherButton10.png", true);
        Utilidades.setLabelImage(icoTop12, "src/launcheruniversae/img/LauncherButton11.png", true);
        Utilidades.setLabelImage(icoTop13, "src/launcheruniversae/img/LauncherButton12.png", true);
        Utilidades.setLabelImage(icoTop14, "src/launcheruniversae/img/LauncherButton13.png", true);
        Utilidades.addHoverEffect(icoTop1, "src/launcheruniversae/img/LauncherButton0.png", 0.9);
        Utilidades.addHoverEffect(icoTop2, "src/launcheruniversae/img/LauncherButton1.png", 0.9);
        Utilidades.addHoverEffect(icoTop3, "src/launcheruniversae/img/LauncherButton2.png", 0.9);
        Utilidades.addHoverEffect(icoTop4, "src/launcheruniversae/img/LauncherButton3.png", 0.9);
        Utilidades.addHoverEffect(icoTop5, "src/launcheruniversae/img/LauncherButton4.png", 0.9);
        Utilidades.addHoverEffect(icoTop6, "src/launcheruniversae/img/LauncherButton5.png", 0.9);
        Utilidades.addHoverEffect(icoTop7, "src/launcheruniversae/img/LauncherButton6.png", 0.9);
        Utilidades.addHoverEffect(icoTop8, "src/launcheruniversae/img/LauncherButton7.png", 0.9);
        Utilidades.addHoverEffect(icoTop9, "src/launcheruniversae/img/LauncherButton8.png", 0.9);
        Utilidades.addHoverEffect(icoTop10, "src/launcheruniversae/img/LauncherButton9.png", 0.9);
        Utilidades.addHoverEffect(icoTop11, "src/launcheruniversae/img/LauncherButton10.png", 0.9);
        Utilidades.addHoverEffect(icoTop12, "src/launcheruniversae/img/LauncherButton11.png", 0.9);
        Utilidades.addHoverEffect(icoTop13, "src/launcheruniversae/img/LauncherButton12.png", 0.9);
        Utilidades.addHoverEffect(icoTop14, "src/launcheruniversae/img/LauncherButton13.png", 0.9);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JLabel icoTop1;
    private javax.swing.JLabel icoTop10;
    private javax.swing.JLabel icoTop11;
    private javax.swing.JLabel icoTop12;
    private javax.swing.JLabel icoTop13;
    private javax.swing.JLabel icoTop14;
    private javax.swing.JLabel icoTop2;
    private javax.swing.JLabel icoTop3;
    private javax.swing.JLabel icoTop4;
    private javax.swing.JLabel icoTop5;
    private javax.swing.JLabel icoTop6;
    private javax.swing.JLabel icoTop7;
    private javax.swing.JLabel icoTop8;
    private javax.swing.JLabel icoTop9;
    private javax.swing.JLabel labelBgImage;
    private javax.swing.JPanel topIcons;
    // End of variables declaration//GEN-END:variables
}
