
package launcheruniversae;

/**
 *
 * @author Victor Arroyo
 */
public class PageCarrusel extends javax.swing.JPanel {

    /**
     * Creates new form Page_EPIS
     */
    public PageCarrusel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorEmbDesembHelic = new javax.swing.JPanel();
        imgMainCarrusel = new javax.swing.JLabel();
        imgCarruselFondoDerecha = new javax.swing.JLabel();
        imgCarruselFondoIzquierda = new javax.swing.JLabel();
        PanelIndiceImagenes = new javax.swing.JPanel();
        imgBolaCarrusel0 = new javax.swing.JLabel();
        imgBolaCarrusel1 = new javax.swing.JLabel();
        imgBolaCarrusel2 = new javax.swing.JLabel();
        imgBolaCarrusel3 = new javax.swing.JLabel();
        imgBolaCarrusel4 = new javax.swing.JLabel();
        imgComenzar = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1430, 730));
        setMinimumSize(new java.awt.Dimension(1430, 730));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1430, 730));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedorEmbDesembHelic.setMaximumSize(new java.awt.Dimension(1430, 730));
        contenedorEmbDesembHelic.setMinimumSize(new java.awt.Dimension(1430, 730));
        contenedorEmbDesembHelic.setName(""); // NOI18N
        contenedorEmbDesembHelic.setOpaque(false);
        contenedorEmbDesembHelic.setPreferredSize(new java.awt.Dimension(1430, 730));
        contenedorEmbDesembHelic.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgMainCarrusel.setBackground(new java.awt.Color(51, 51, 51));
        imgMainCarrusel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgMainCarrusel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/page2/Embarque0.png"))); // NOI18N
        imgMainCarrusel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgMainCarrusel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        contenedorEmbDesembHelic.add(imgMainCarrusel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 860, 490));

        imgCarruselFondoDerecha.setBackground(new java.awt.Color(102, 102, 102));
        imgCarruselFondoDerecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        imgCarruselFondoDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/page2/Cuadrado fondo enfocado.png"))); // NOI18N
        imgCarruselFondoDerecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contenedorEmbDesembHelic.add(imgCarruselFondoDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 40, 130, 420));

        imgCarruselFondoIzquierda.setBackground(new java.awt.Color(102, 102, 102));
        imgCarruselFondoIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/page2/Cuadrado fondo enfocado.png"))); // NOI18N
        imgCarruselFondoIzquierda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contenedorEmbDesembHelic.add(imgCarruselFondoIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 140, 420));

        PanelIndiceImagenes.setOpaque(false);

        imgBolaCarrusel0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/page2/PuntoCarruselEmpty.png"))); // NOI18N
        imgBolaCarrusel0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelIndiceImagenes.add(imgBolaCarrusel0);

        imgBolaCarrusel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/page2/PuntoCarruselEmpty.png"))); // NOI18N
        imgBolaCarrusel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelIndiceImagenes.add(imgBolaCarrusel1);

        imgBolaCarrusel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/page2/PuntoCarruselEmpty.png"))); // NOI18N
        imgBolaCarrusel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelIndiceImagenes.add(imgBolaCarrusel2);

        imgBolaCarrusel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/page2/PuntoCarruselEmpty.png"))); // NOI18N
        imgBolaCarrusel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelIndiceImagenes.add(imgBolaCarrusel3);

        imgBolaCarrusel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/page2/PuntoCarruselEmpty.png"))); // NOI18N
        imgBolaCarrusel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelIndiceImagenes.add(imgBolaCarrusel4);

        contenedorEmbDesembHelic.add(PanelIndiceImagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 110, -1));

        imgComenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/page2/Comenzar.png"))); // NOI18N
        imgComenzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contenedorEmbDesembHelic.add(imgComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1284, 806, 260, 50));

        labelTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        labelTitulo.setOpaque(true);
        contenedorEmbDesembHelic.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 1150, 40));

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(null);
        txtDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDescripcion.setOpaque(false);
        txtDescripcion.setBackground(new java.awt.Color(0, 0, 0, 0));
        jScrollPane1.setViewportView(txtDescripcion);
        jScrollPane1.setViewportView(txtDescripcion);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);

        contenedorEmbDesembHelic.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 1170, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/page2/Barrita aislada descripción.png"))); // NOI18N
        contenedorEmbDesembHelic.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 10, 40));

        add(contenedorEmbDesembHelic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 870));
        contenedorEmbDesembHelic.getAccessibleContext().setAccessibleName("");
        contenedorEmbDesembHelic.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelIndiceImagenes;
    private javax.swing.JPanel contenedorEmbDesembHelic;
    private javax.swing.JLabel imgBolaCarrusel0;
    private javax.swing.JLabel imgBolaCarrusel1;
    private javax.swing.JLabel imgBolaCarrusel2;
    private javax.swing.JLabel imgBolaCarrusel3;
    private javax.swing.JLabel imgBolaCarrusel4;
    private javax.swing.JLabel imgCarruselFondoDerecha;
    private javax.swing.JLabel imgCarruselFondoIzquierda;
    private javax.swing.JLabel imgComenzar;
    private javax.swing.JLabel imgMainCarrusel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
