package launcheruniversae;

import java.util.ArrayList;
import utilidades.Utilidades;

/**
 *
 * @author Victor Arroyo
 */
public class PageCarruselGame extends javax.swing.JPanel {

    PageGame pageGame = new PageGame();
    private ArrayList<String> listaRutasCarrusel;
    int pos = 0; // posicion carrusel
    private int juegoMostrar = pageGame.getJuegoSeleccionado(); // 1 -- 6

    public PageCarruselGame() {
        initComponents();
        if (juegoMostrar == 1) {
            asignarCarrusel1();
            listaRutasCarrusel.toString();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorEmbDesembHelic = new javax.swing.JPanel();
        imgMainCarrusel = new javax.swing.JLabel();
        imgCarruselFondoDerecha = new javax.swing.JLabel();
        imgCarruselFondoIzquierda = new javax.swing.JLabel();
        PanelIndiceImagenes = new javax.swing.JPanel();
        imgBolaCarrusel0 = new javax.swing.JLabel();
        imgBolaCarrusel1 = new javax.swing.JLabel();
        imgBolaCarrusel2 = new javax.swing.JLabel();
        imgBolaCarrusel3 = new javax.swing.JLabel();
        imgBolaCarrusel4 = new javax.swing.JLabel();
        imgComenzar = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        botonIzquierdaCarrusel = new javax.swing.JLabel();
        botonDerechaCarrusel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1430, 730));
        setMinimumSize(new java.awt.Dimension(1430, 730));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1430, 730));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedorEmbDesembHelic.setMaximumSize(new java.awt.Dimension(1430, 730));
        contenedorEmbDesembHelic.setMinimumSize(new java.awt.Dimension(1430, 730));
        contenedorEmbDesembHelic.setName(""); // NOI18N
        contenedorEmbDesembHelic.setOpaque(false);
        contenedorEmbDesembHelic.setPreferredSize(new java.awt.Dimension(1430, 730));
        contenedorEmbDesembHelic.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgMainCarrusel.setBackground(new java.awt.Color(51, 51, 51));
        imgMainCarrusel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgMainCarrusel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/PageCarruselGame/Embarque0.png"))); // NOI18N
        imgMainCarrusel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgMainCarrusel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        contenedorEmbDesembHelic.add(imgMainCarrusel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 860, 490));

        imgCarruselFondoDerecha.setBackground(new java.awt.Color(102, 102, 102));
        imgCarruselFondoDerecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        imgCarruselFondoDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/PageCarruselGame/Cuadrado fondo enfocado.png"))); // NOI18N
        imgCarruselFondoDerecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgCarruselFondoDerecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgCarruselFondoDerechaMouseClicked(evt);
            }
        });
        contenedorEmbDesembHelic.add(imgCarruselFondoDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 40, 130, 420));

        imgCarruselFondoIzquierda.setBackground(new java.awt.Color(102, 102, 102));
        imgCarruselFondoIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/PageCarruselGame/Cuadrado fondo enfocado.png"))); // NOI18N
        imgCarruselFondoIzquierda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgCarruselFondoIzquierda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgCarruselFondoIzquierdaMouseClicked(evt);
            }
        });
        contenedorEmbDesembHelic.add(imgCarruselFondoIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 140, 420));

        PanelIndiceImagenes.setOpaque(false);

        imgBolaCarrusel0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/PageCarruselGame/PuntoCarruselEmpty.png"))); // NOI18N
        imgBolaCarrusel0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelIndiceImagenes.add(imgBolaCarrusel0);

        imgBolaCarrusel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/PageCarruselGame/PuntoCarruselEmpty.png"))); // NOI18N
        imgBolaCarrusel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelIndiceImagenes.add(imgBolaCarrusel1);

        imgBolaCarrusel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/PageCarruselGame/PuntoCarruselEmpty.png"))); // NOI18N
        imgBolaCarrusel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelIndiceImagenes.add(imgBolaCarrusel2);

        imgBolaCarrusel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/PageCarruselGame/PuntoCarruselEmpty.png"))); // NOI18N
        imgBolaCarrusel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelIndiceImagenes.add(imgBolaCarrusel3);

        imgBolaCarrusel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/PageCarruselGame/PuntoCarruselEmpty.png"))); // NOI18N
        imgBolaCarrusel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelIndiceImagenes.add(imgBolaCarrusel4);

        contenedorEmbDesembHelic.add(PanelIndiceImagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 110, -1));

        imgComenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/PageCarruselGame/Comenzar.png"))); // NOI18N
        imgComenzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contenedorEmbDesembHelic.add(imgComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1284, 806, 260, 50));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelTitulo.setText("Embarque y desembarque en helicoptero");
        labelTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        contenedorEmbDesembHelic.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 750, 40));

        jScrollPane1.setBorder(null);
        jScrollPane1.setWheelScrollingEnabled(false);

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(8);
        txtDescripcion.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. \n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum\n");
        txtDescripcion.setBorder(null);
        txtDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDescripcion.setOpaque(false);
        txtDescripcion.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtDescripcion.setBorder(null);
        jScrollPane1.setViewportView(txtDescripcion);
        jScrollPane1.setViewportView(txtDescripcion);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);

        contenedorEmbDesembHelic.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 760, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/PageCarruselGame/Barrita aislada descripción.png"))); // NOI18N
        contenedorEmbDesembHelic.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 10, 40));

        botonIzquierdaCarrusel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botonIzquierdaCarrusel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/PageCarruselGame/Flecha izquierda.png"))); // NOI18N
        botonIzquierdaCarrusel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIzquierdaCarrusel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonIzquierdaCarruselMouseClicked(evt);
            }
        });
        contenedorEmbDesembHelic.add(botonIzquierdaCarrusel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 30, 50));

        botonDerechaCarrusel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonDerechaCarrusel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcheruniversae/img/PageCarruselGame/Flecha derecha.png"))); // NOI18N
        botonDerechaCarrusel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonDerechaCarrusel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonDerechaCarruselMouseClicked(evt);
            }
        });
        contenedorEmbDesembHelic.add(botonDerechaCarrusel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 230, 30, 50));

        add(contenedorEmbDesembHelic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 870));
        contenedorEmbDesembHelic.getAccessibleContext().setAccessibleName("");
        contenedorEmbDesembHelic.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void imgCarruselFondoDerechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgCarruselFondoDerechaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_imgCarruselFondoDerechaMouseClicked

    private void botonDerechaCarruselMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDerechaCarruselMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonDerechaCarruselMouseClicked

    private void imgCarruselFondoIzquierdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgCarruselFondoIzquierdaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_imgCarruselFondoIzquierdaMouseClicked

    private void botonIzquierdaCarruselMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIzquierdaCarruselMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonIzquierdaCarruselMouseClicked

    private void asignarCarrusel1() {

        if (juegoMostrar == 1) {
            listaRutasCarrusel = Utilidades.createStringList("src/launcheruniversae/img/PageCarruselGame/", "Embarque", ".png", 5);
        } else if (juegoMostrar == 2) {
            listaRutasCarrusel = Utilidades.createStringList("src/launcheruniversae/img/PageCarruselGame/", "Hemorragia", ".png", 5);
        } else if (juegoMostrar == 3) {
            listaRutasCarrusel = Utilidades.createStringList("src/launcheruniversae/img/PageCarruselGame/", "Extincion", ".png", 5);
        } else if (juegoMostrar == 4) {
            listaRutasCarrusel = Utilidades.createStringList("src/launcheruniversae/img/PageCarruselGame/", "EPIS", ".png", 5);
        } else if (juegoMostrar == 5) {
            listaRutasCarrusel = Utilidades.createStringList("src/launcheruniversae/img/PageCarruselGame/", "Helicoptero", ".png", 5);
        } else if (juegoMostrar == 6) {
            listaRutasCarrusel = Utilidades.createStringList("src/launcheruniversae/img/PageCarruselGame/", "Ascensor", ".png", 5);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelIndiceImagenes;
    private javax.swing.JLabel botonDerechaCarrusel;
    private javax.swing.JLabel botonIzquierdaCarrusel;
    private javax.swing.JPanel contenedorEmbDesembHelic;
    private javax.swing.JLabel imgBolaCarrusel0;
    private javax.swing.JLabel imgBolaCarrusel1;
    private javax.swing.JLabel imgBolaCarrusel2;
    private javax.swing.JLabel imgBolaCarrusel3;
    private javax.swing.JLabel imgBolaCarrusel4;
    private javax.swing.JLabel imgCarruselFondoDerecha;
    private javax.swing.JLabel imgCarruselFondoIzquierda;
    private javax.swing.JLabel imgComenzar;
    private javax.swing.JLabel imgMainCarrusel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
