package launcheruniversae;

import utilidades.Utilidades;

/**
 *
 * @author Víctor Arroyo
 */
public class PageBotones extends javax.swing.JPanel {

    PageCarrusel carrusel = new PageCarrusel();
    
    public PageBotones() {
        initComponents();
        agregarImagenesPage1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        ico1_EmbDesemHelic = new javax.swing.JLabel();
        ico2_ProtocoloHemorr = new javax.swing.JLabel();
        ico3_ManiobrasExtincion = new javax.swing.JLabel();
        ico4_Epis = new javax.swing.JLabel();
        ico5_SeñalizacionHelic = new javax.swing.JLabel();
        ico6_RescateAscensor = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1550, 870));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1550, 870));

        content.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        content.setMaximumSize(new java.awt.Dimension(1430, 730));
        content.setMinimumSize(new java.awt.Dimension(1430, 730));
        content.setOpaque(false);
        content.setPreferredSize(new java.awt.Dimension(1430, 730));
        content.setLayout(new java.awt.GridLayout(2, 3, 80, 110));

        ico1_EmbDesemHelic.setBackground(new java.awt.Color(10, 38, 72));
        ico1_EmbDesemHelic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico1_EmbDesemHelic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ico1_EmbDesemHelic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ico1_EmbDesemHelic.setMaximumSize(new java.awt.Dimension(380, 291));
        ico1_EmbDesemHelic.setMinimumSize(new java.awt.Dimension(380, 291));
        ico1_EmbDesemHelic.setPreferredSize(new java.awt.Dimension(380, 291));
        ico1_EmbDesemHelic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico1_EmbDesemHelicMouseClicked(evt);
            }
        });
        content.add(ico1_EmbDesemHelic);

        ico2_ProtocoloHemorr.setBackground(new java.awt.Color(10, 38, 72));
        ico2_ProtocoloHemorr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico2_ProtocoloHemorr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ico2_ProtocoloHemorr.setFocusCycleRoot(true);
        ico2_ProtocoloHemorr.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ico2_ProtocoloHemorr.setMaximumSize(new java.awt.Dimension(380, 291));
        ico2_ProtocoloHemorr.setMinimumSize(new java.awt.Dimension(380, 291));
        ico2_ProtocoloHemorr.setPreferredSize(new java.awt.Dimension(380, 291));
        ico2_ProtocoloHemorr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico2_ProtocoloHemorrMouseClicked(evt);
            }
        });
        content.add(ico2_ProtocoloHemorr);

        ico3_ManiobrasExtincion.setBackground(new java.awt.Color(10, 38, 72));
        ico3_ManiobrasExtincion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico3_ManiobrasExtincion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ico3_ManiobrasExtincion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ico3_ManiobrasExtincion.setMaximumSize(new java.awt.Dimension(380, 291));
        ico3_ManiobrasExtincion.setMinimumSize(new java.awt.Dimension(380, 291));
        ico3_ManiobrasExtincion.setPreferredSize(new java.awt.Dimension(380, 291));
        ico3_ManiobrasExtincion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico3_ManiobrasExtincionMouseClicked(evt);
            }
        });
        content.add(ico3_ManiobrasExtincion);

        ico4_Epis.setBackground(new java.awt.Color(10, 38, 72));
        ico4_Epis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico4_Epis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ico4_Epis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ico4_Epis.setMaximumSize(new java.awt.Dimension(380, 291));
        ico4_Epis.setMinimumSize(new java.awt.Dimension(380, 291));
        ico4_Epis.setPreferredSize(new java.awt.Dimension(380, 291));
        ico4_Epis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico4_EpisMouseClicked(evt);
            }
        });
        content.add(ico4_Epis);

        ico5_SeñalizacionHelic.setBackground(new java.awt.Color(10, 38, 72));
        ico5_SeñalizacionHelic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico5_SeñalizacionHelic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ico5_SeñalizacionHelic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ico5_SeñalizacionHelic.setMaximumSize(new java.awt.Dimension(380, 291));
        ico5_SeñalizacionHelic.setMinimumSize(new java.awt.Dimension(380, 291));
        ico5_SeñalizacionHelic.setPreferredSize(new java.awt.Dimension(380, 291));
        ico5_SeñalizacionHelic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico5_SeñalizacionHelicMouseClicked(evt);
            }
        });
        content.add(ico5_SeñalizacionHelic);

        ico6_RescateAscensor.setBackground(new java.awt.Color(204, 102, 255));
        ico6_RescateAscensor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico6_RescateAscensor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ico6_RescateAscensor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ico6_RescateAscensor.setMaximumSize(new java.awt.Dimension(380, 291));
        ico6_RescateAscensor.setMinimumSize(new java.awt.Dimension(380, 291));
        ico6_RescateAscensor.setPreferredSize(new java.awt.Dimension(380, 291));
        ico6_RescateAscensor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico6_RescateAscensorMouseClicked(evt);
            }
        });
        content.add(ico6_RescateAscensor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 1550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ico1_EmbDesemHelicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico1_EmbDesemHelicMouseClicked
        Utilidades.showPanel(carrusel, content);
        //Asignar que el carrusel empiece con la imagen embarque desembarque helicop
    }//GEN-LAST:event_ico1_EmbDesemHelicMouseClicked

    private void ico2_ProtocoloHemorrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico2_ProtocoloHemorrMouseClicked
        Utilidades.showPanel(carrusel, content);
        //Asignar que el carrusel empiece con la imagen protocolo hemorragia
    }//GEN-LAST:event_ico2_ProtocoloHemorrMouseClicked

    private void ico3_ManiobrasExtincionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico3_ManiobrasExtincionMouseClicked
        Utilidades.showPanel(carrusel, content);
        //Asignar que el carrusel empiece con la imagen maniobras extincion
    }//GEN-LAST:event_ico3_ManiobrasExtincionMouseClicked

    private void ico4_EpisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico4_EpisMouseClicked
        Utilidades.showPanel(carrusel, content);
        //Asignar que el carrusel empiece con la imagen EPIS
    }//GEN-LAST:event_ico4_EpisMouseClicked

    private void ico5_SeñalizacionHelicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico5_SeñalizacionHelicMouseClicked
        Utilidades.showPanel(carrusel, content);
        //Asignar que el carrusel empiece con la imagen señalizacion helic
    }//GEN-LAST:event_ico5_SeñalizacionHelicMouseClicked

    private void ico6_RescateAscensorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico6_RescateAscensorMouseClicked
        Utilidades.showPanel(carrusel, content);
        //Asignar que el carrusel empiece con la imagen  rescate ascensor
    }//GEN-LAST:event_ico6_RescateAscensorMouseClicked

    private void agregarImagenesPage1() {
        Utilidades.setLabelImage(ico1_EmbDesemHelic, "src/launcheruniversae/img/page1/Grado0.png", true, 0.9);
        Utilidades.setLabelImage(ico2_ProtocoloHemorr, "src/launcheruniversae/img/page1/Grado1.png", true, 0.9);
        Utilidades.setLabelImage(ico3_ManiobrasExtincion, "src/launcheruniversae/img/page1/Grado2.png", true, 0.9);
        Utilidades.setLabelImage(ico4_Epis, "src/launcheruniversae/img/page1/Grado3.png", true, 0.9);
        Utilidades.setLabelImage(ico5_SeñalizacionHelic, "src/launcheruniversae/img/page1/Grado4.png", true, 0.9);
        Utilidades.setLabelImage(ico6_RescateAscensor, "src/launcheruniversae/img/page1/Grado5.png", true, 0.9);
        Utilidades.addHoverEffect(ico1_EmbDesemHelic, "src/launcheruniversae/img/page1/Grado0.png", 0.9);
        Utilidades.addHoverEffect(ico2_ProtocoloHemorr, "src/launcheruniversae/img/page1/Grado1.png", 0.9);
        Utilidades.addHoverEffect(ico3_ManiobrasExtincion, "src/launcheruniversae/img/page1/Grado2.png", 0.9);
        Utilidades.addHoverEffect(ico4_Epis, "src/launcheruniversae/img/page1/Grado3.png", 0.9);
        Utilidades.addHoverEffect(ico5_SeñalizacionHelic, "src/launcheruniversae/img/page1/Grado4.png", 0.9);
        Utilidades.addHoverEffect(ico6_RescateAscensor, "src/launcheruniversae/img/page1/Grado5.png", 0.9);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JLabel ico1_EmbDesemHelic;
    private javax.swing.JLabel ico2_ProtocoloHemorr;
    private javax.swing.JLabel ico3_ManiobrasExtincion;
    private javax.swing.JLabel ico4_Epis;
    private javax.swing.JLabel ico5_SeñalizacionHelic;
    private javax.swing.JLabel ico6_RescateAscensor;
    // End of variables declaration//GEN-END:variables
}
